/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package mx.com.nmp.historicoprecios.api;

import io.swagger.annotations.*;
import mx.com.nmp.historicoprecios.model.BadRequest;
import mx.com.nmp.historicoprecios.model.GeneralResponse;
import mx.com.nmp.historicoprecios.model.HistoricoPrecios;
import mx.com.nmp.historicoprecios.model.InternalServerError;
import mx.com.nmp.historicoprecios.model.InvalidAuthentication;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-19T17:57:16.669Z")

@Api(value = "historico", description = "the historico API")
public interface HistoricoApi {

    @ApiOperation(value = "Almacenar el histórico de precios", nickname = "historicoPreciosPost", notes = "Almacenar el histórico de precios en elasticsearch. ### Seguridad Para poder realizar el consumo del recuros deberá de estar autorizado. Para esto tiene que enviar la llave en el encabezado HTTP: * 'X-API-KEY: eyJ4NXQjUzI1NiI6IkFTS1ESG42` ", response = GeneralResponse.class, authorizations = {
        @Authorization(value = "apiKey")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Almacenado de manera exitosa", response = GeneralResponse.class),
        @ApiResponse(code = 400, message = "Error en el mensaje de petición, verifique la información", response = BadRequest.class),
        @ApiResponse(code = 401, message = "Error de autorización en el uso del recurso", response = InvalidAuthentication.class),
        @ApiResponse(code = 500, message = "Error interno del servidor", response = InternalServerError.class) })
    @RequestMapping(value = "/historico/precios",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    //ResponseEntity<GeneralResponse> historicoPreciosPost(@ApiParam(value = "Usuario de sistema que lanza la petición" ,required=true) @RequestHeader(value="usuario", required=true) String usuario,@ApiParam(value = "Cuerpo de la petición" ,required=true )  @Valid @RequestBody HistoricoPrecios peticion);
    ResponseEntity<?> historicoPreciosPost(@ApiParam(value = "Usuario de sistema que lanza la petición" ,required=true) @RequestHeader(value="usuario", required=true) String usuario,@ApiParam(value = "Cuerpo de la petición" ,required=true )  @Valid @RequestBody HistoricoPrecios peticion);
}
