/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.12).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package mx.com.nmp.valormonte.api;

import mx.com.nmp.valormonte.model.BadRequest;
import mx.com.nmp.valormonte.model.CalculoValorMonteReq;
import mx.com.nmp.valormonte.model.CalculoValorMonteRes;
import mx.com.nmp.valormonte.model.InternalServerError;
import mx.com.nmp.valormonte.model.InvalidAuthentication;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-01-30T17:34:52.695Z")

@Api(value = "valorMonte", description = "the valorMonte API")
public interface ValorMonteApi {

    @ApiOperation(value = "Realiza cálculo del valor monte actual de una partida y/o producto.", nickname = "calcularValorMontePOST", notes = "Se realiza el cálculo del valor monte con la información actual de la partida.   En caso de no obtener los valores necesarios para realizar el cálculo, se deberá consultar la información de las partidas en ElasticSearch. ", response = CalculoValorMonteRes.class, authorizations = {
        @Authorization(value = "apiKey"),
        @Authorization(value = "apiSecret")
    }, tags={ "Valor Monte Actualizado", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Procesamiento de archivo en curso", response = CalculoValorMonteRes.class),
        @ApiResponse(code = 400, message = "Error en el mensaje de petición, verifique la información", response = BadRequest.class),
        @ApiResponse(code = 401, message = "Error de autorización en el uso del recurso", response = InvalidAuthentication.class),
        @ApiResponse(code = 500, message = "Error interno del servidor", response = InternalServerError.class) })
    @RequestMapping(value = "/valorMonte",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
     ResponseEntity<?> calcularValorMontePOST(@ApiParam(value = "Usuario en el sistema origen que lanza la petición" ,required=true) @RequestHeader(value="usuario", required=true) String usuario,@ApiParam(value = "Sistema que origina la petición" ,required=true, allowableValues="portalMotorDescuentosAutomatizados") @RequestHeader(value="origen", required=true) String origen,@ApiParam(value = "Destino final de la información" ,required=true, allowableValues="bluemix, mockserver") @RequestHeader(value="destino", required=true) String destino,@ApiParam(value = ""  )  @Valid  @RequestBody CalculoValorMonteReq valorMonteReq);

}
