/*
 * Motor de Descuentos Automatizados
 * ### Descripción   API que permite interactuar con las diferentes funcionalidades en el proyecto Motor de Descuentos Automatizados de Nacional Monte de Piedad.  ### Capacidades   * Administración de Usuarios.      El alta de usuarios por medio del api no está soportada, se necesita realizar un ticket a mesa de ayuda para dar de alta un usuario en AD.   * Consolidados.   * Cálculo valor monte.   * Tablas de referencia.   * Establecimiento de precios   * Histórico de precios   * Escenarios dinámicos   * Gestión de escenarios   * Simulación   * Probar la existencia de una regla ### Seguridad   Antes de usar este recurso, el consumidor deberá ser autorizado. Para ello el consumidor enviará una llave en el encabezado HTTP. Ejemplo:   * `X-API-KEY: eyJ4NXQjUzI1NiI6IkFTS1ESG42`    
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sgonzalez@spsolutions.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package mx.com.nmp.escenariosdinamicos.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * InvalidValue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-17T23:16:32.685Z")
public class InvalidValue   {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("message")
  private String message = null;

  public InvalidValue code(String code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   **/
  @JsonProperty("code")
  @ApiModelProperty(example = "NMP-MDA-404", value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public InvalidValue message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   **/
  @JsonProperty("message")
  @ApiModelProperty(example = "La regla no cumple con los parametros proporcionados", value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvalidValue invalidValue = (InvalidValue) o;
    return Objects.equals(this.code, invalidValue.code) &&
        Objects.equals(this.message, invalidValue.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvalidValue {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

