/*
 * Motor de Descuentos Automatizados
 * ### Descripción   API que permite interactuar con las diferentes funcionalidades en el proyecto Motor de Descuentos Automatizados de Nacional Monte de Piedad.  ### Capacidades   * Administración de Usuarios.      El alta de usuarios por medio del api no está soportada, se necesita realizar un ticket a mesa de ayuda para dar de alta un usuario en AD.   * Consolidados.   * Cálculo valor monte.   * Tablas de referencia.   * Establecimiento de precios   * Histórico de precios   * Escenarios dinámicos   * Gestión de escenarios   * Simulación   * Probar la existencia de una regla ### Seguridad   Antes de usar este recurso, el consumidor deberá ser autorizado. Para ello el consumidor enviará una llave en el encabezado HTTP. Ejemplo:   * `X-API-KEY: eyJ4NXQjUzI1NiI6IkFTS1ESG42`    
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sgonzalez@spsolutions.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package mx.com.nmp.escenariosdinamicos.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * SuccessfulResponseRule
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-17T23:16:32.685Z")
public class SuccessfulResponseRule   {
  @JsonProperty("existe")
  private String existe = null;

  public SuccessfulResponseRule existe(String existe) {
    this.existe = existe;
    return this;
  }

  /**
   * Get existe
   * @return existe
   **/
  @JsonProperty("existe")
  @ApiModelProperty(example = "Regla existente", value = "")
  public String getExiste() {
    return existe;
  }

  public void setExiste(String existe) {
    this.existe = existe;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuccessfulResponseRule successfulResponseRule = (SuccessfulResponseRule) o;
    return Objects.equals(this.existe, successfulResponseRule.existe);
  }

  @Override
  public int hashCode() {
    return Objects.hash(existe);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuccessfulResponseRule {\n");
    
    sb.append("    existe: ").append(toIndentedString(existe)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

